export const add = () => ({type: 'ADD'})
export const add2 = (number) => ({type: 'ADD2', number})
export const minus2 = (number) => ({type: 'MINUS2', number})
export const minus = () => ({ type: 'MINUS'})
export const reset = () => ({type: 'RESET'})